### ISSUE TITLE
bug in `enableOTFeature`

### ISSUE THREAD

**Issue by graphicore** [kontur/jquery-fontsampler#2]
Hi, I just had a brief look at the code and spotted what is probably a  bug in:
https://github.com/kontur/jquery-fontsampler/blob/master/src/jquery.fontsampler.js#L78

It is:
```js
if (this.otfeatures.indexOf( args[ 1 ] === -1 ) ) {
```
I belief it should be

```js
if (this.otfeatures.indexOf( args[ 1 ] ) === -1  ) {
```

**Comment by kontur** [comment]
Thanks for the pointer ;)
